# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ProcessKilnImages-dlg.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(826, 700)
        self.verticalLayoutWidget = QtWidgets.QWidget(Dialog)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 471, 671))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtWidgets.QWidget(self.verticalLayoutWidget)
        self.widget.setObjectName("widget")
        self.verticalLayout.addWidget(self.widget)
        self.leMsg = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setBold(True)
        font.setWeight(75)
        self.leMsg.setFont(font)
        self.leMsg.setText("")
        self.leMsg.setAlignment(QtCore.Qt.AlignCenter)
        self.leMsg.setObjectName("leMsg")
        self.verticalLayout.addWidget(self.leMsg)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(Dialog)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(490, 10, 328, 358))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 9)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnPrevious = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.btnPrevious.setObjectName("btnPrevious")
        self.horizontalLayout.addWidget(self.btnPrevious)
        self.btnNext = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.btnNext.setObjectName("btnNext")
        self.horizontalLayout.addWidget(self.btnNext)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.labFilename = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.labFilename.setObjectName("labFilename")
        self.horizontalLayout_4.addWidget(self.labFilename)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem1)
        self.btnGreyScale = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.btnGreyScale.setMaximumSize(QtCore.QSize(100, 16777215))
        self.btnGreyScale.setObjectName("btnGreyScale")
        self.horizontalLayout_5.addWidget(self.btnGreyScale)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem2)
        self.btnHistogram = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.btnHistogram.setObjectName("btnHistogram")
        self.horizontalLayout_6.addWidget(self.btnHistogram)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.labThreshold = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labThreshold.sizePolicy().hasHeightForWidth())
        self.labThreshold.setSizePolicy(sizePolicy)
        self.labThreshold.setMinimumSize(QtCore.QSize(50, 0))
        self.labThreshold.setMaximumSize(QtCore.QSize(60, 16777215))
        self.labThreshold.setObjectName("labThreshold")
        self.horizontalLayout_2.addWidget(self.labThreshold)
        self.leThreshold = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.leThreshold.setMaximumSize(QtCore.QSize(30, 16777215))
        self.leThreshold.setMaxLength(4)
        self.leThreshold.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.leThreshold.setObjectName("leThreshold")
        self.horizontalLayout_2.addWidget(self.leThreshold)
        self.hsbThreshold = QtWidgets.QScrollBar(self.verticalLayoutWidget_2)
        self.hsbThreshold.setMaximum(100)
        self.hsbThreshold.setSliderPosition(50)
        self.hsbThreshold.setOrientation(QtCore.Qt.Horizontal)
        self.hsbThreshold.setObjectName("hsbThreshold")
        self.horizontalLayout_2.addWidget(self.hsbThreshold)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.labSigma = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labSigma.sizePolicy().hasHeightForWidth())
        self.labSigma.setSizePolicy(sizePolicy)
        self.labSigma.setMinimumSize(QtCore.QSize(50, 0))
        self.labSigma.setMaximumSize(QtCore.QSize(60, 16777215))
        self.labSigma.setObjectName("labSigma")
        self.horizontalLayout_3.addWidget(self.labSigma)
        self.leSigma = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.leSigma.setMaximumSize(QtCore.QSize(30, 16777215))
        self.leSigma.setMaxLength(4)
        self.leSigma.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.leSigma.setObjectName("leSigma")
        self.horizontalLayout_3.addWidget(self.leSigma)
        self.hsbSigma = QtWidgets.QScrollBar(self.verticalLayoutWidget_2)
        self.hsbSigma.setMaximum(100)
        self.hsbSigma.setSliderPosition(50)
        self.hsbSigma.setOrientation(QtCore.Qt.Horizontal)
        self.hsbSigma.setObjectName("hsbSigma")
        self.horizontalLayout_3.addWidget(self.hsbSigma)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem3)
        self.btnApplyMask = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.btnApplyMask.setObjectName("btnApplyMask")
        self.horizontalLayout_7.addWidget(self.btnApplyMask)
        self.verticalLayout_2.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem4)
        self.btnFindRegions = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.btnFindRegions.setObjectName("btnFindRegions")
        self.horizontalLayout_8.addWidget(self.btnFindRegions)
        self.verticalLayout_2.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem5)
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label.setObjectName("label")
        self.horizontalLayout_9.addWidget(self.label)
        self.leWidth = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.leWidth.setMaximumSize(QtCore.QSize(30, 16777215))
        self.leWidth.setObjectName("leWidth")
        self.horizontalLayout_9.addWidget(self.leWidth)
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_9.addWidget(self.label_2)
        self.leHeight = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.leHeight.setMaximumSize(QtCore.QSize(30, 16777215))
        self.leHeight.setObjectName("leHeight")
        self.horizontalLayout_9.addWidget(self.leHeight)
        self.label_5 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_9.addWidget(self.label_5)
        self.leDigits = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.leDigits.setMaximumSize(QtCore.QSize(40, 16777215))
        self.leDigits.setObjectName("leDigits")
        self.horizontalLayout_9.addWidget(self.leDigits)
        self.btnSplit = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.btnSplit.setObjectName("btnSplit")
        self.horizontalLayout_9.addWidget(self.btnSplit)
        self.verticalLayout_2.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem6)
        self.btnSave = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.btnSave.setObjectName("btnSave")
        self.horizontalLayout_10.addWidget(self.btnSave)
        self.verticalLayout_2.addLayout(self.horizontalLayout_10)
        self.cbAutoProcess = QtWidgets.QCheckBox(self.verticalLayoutWidget_2)
        self.cbAutoProcess.setObjectName("cbAutoProcess")
        self.verticalLayout_2.addWidget(self.cbAutoProcess)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.btnPrevious.setText(_translate("Dialog", "Previous"))
        self.btnNext.setText(_translate("Dialog", "Next"))
        self.labFilename.setText(_translate("Dialog", "               "))
        self.btnGreyScale.setText(_translate("Dialog", "Grey Scale"))
        self.btnHistogram.setText(_translate("Dialog", "Histogram"))
        self.labThreshold.setText(_translate("Dialog", "Threshold: "))
        self.leThreshold.setText(_translate("Dialog", ".50"))
        self.labSigma.setText(_translate("Dialog", "Sigma:"))
        self.leSigma.setText(_translate("Dialog", "5"))
        self.btnApplyMask.setText(_translate("Dialog", "Apply Mask"))
        self.btnFindRegions.setText(_translate("Dialog", "Find Regions"))
        self.label.setText(_translate("Dialog", "Width:"))
        self.leWidth.setText(_translate("Dialog", "150"))
        self.label_2.setText(_translate("Dialog", "Height:"))
        self.leHeight.setText(_translate("Dialog", "150"))
        self.label_5.setText(_translate("Dialog", "Digits:"))
        self.btnSplit.setText(_translate("Dialog", "Split"))
        self.btnSave.setText(_translate("Dialog", "Save"))
        self.cbAutoProcess.setText(_translate("Dialog", "CheckBox"))

