# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ProcessKilnImages.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(457, 326)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.vboxlayout = QtWidgets.QVBoxLayout()
        self.vboxlayout.setContentsMargins(-1, -1, 0, 14)
        self.vboxlayout.setObjectName("vboxlayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnPrevious = QtWidgets.QPushButton(Form)
        self.btnPrevious.setObjectName("btnPrevious")
        self.horizontalLayout.addWidget(self.btnPrevious)
        self.btnNext = QtWidgets.QPushButton(Form)
        self.btnNext.setObjectName("btnNext")
        self.horizontalLayout.addWidget(self.btnNext)
        self.vboxlayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem)
        self.btnGreyScale = QtWidgets.QPushButton(Form)
        self.btnGreyScale.setMaximumSize(QtCore.QSize(100, 16777215))
        self.btnGreyScale.setObjectName("btnGreyScale")
        self.horizontalLayout_5.addWidget(self.btnGreyScale)
        self.vboxlayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem1)
        self.btnHistogram = QtWidgets.QPushButton(Form)
        self.btnHistogram.setObjectName("btnHistogram")
        self.horizontalLayout_6.addWidget(self.btnHistogram)
        self.vboxlayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMinimumSize(QtCore.QSize(50, 0))
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.hsbThreshold = QtWidgets.QScrollBar(Form)
        self.hsbThreshold.setOrientation(QtCore.Qt.Horizontal)
        self.hsbThreshold.setObjectName("hsbThreshold")
        self.horizontalLayout_2.addWidget(self.hsbThreshold)
        self.vboxlayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setMinimumSize(QtCore.QSize(50, 0))
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.hsbSigma = QtWidgets.QScrollBar(Form)
        self.hsbSigma.setOrientation(QtCore.Qt.Horizontal)
        self.hsbSigma.setObjectName("hsbSigma")
        self.horizontalLayout_3.addWidget(self.hsbSigma)
        self.vboxlayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem2)
        self.btnApplyMask = QtWidgets.QPushButton(Form)
        self.btnApplyMask.setObjectName("btnApplyMask")
        self.horizontalLayout_7.addWidget(self.btnApplyMask)
        self.vboxlayout.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem3)
        self.btnFindRegions = QtWidgets.QPushButton(Form)
        self.btnFindRegions.setObjectName("btnFindRegions")
        self.horizontalLayout_8.addWidget(self.btnFindRegions)
        self.vboxlayout.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_4.addWidget(self.label_5)
        self.leDigits = QtWidgets.QLineEdit(Form)
        self.leDigits.setObjectName("leDigits")
        self.horizontalLayout_4.addWidget(self.leDigits)
        self.vboxlayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem4)
        self.pushButton_5 = QtWidgets.QPushButton(Form)
        self.pushButton_5.setObjectName("pushButton_5")
        self.horizontalLayout_9.addWidget(self.pushButton_5)
        self.vboxlayout.addLayout(self.horizontalLayout_9)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.vboxlayout.addItem(spacerItem5)
        self.gridLayout.addLayout(self.vboxlayout, 0, 1, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.labOriginal = QtWidgets.QLabel(Form)
        self.labOriginal.setMinimumSize(QtCore.QSize(250, 100))
        self.labOriginal.setObjectName("labOriginal")
        self.verticalLayout.addWidget(self.labOriginal)
        self.labHistogram = QtWidgets.QLabel(Form)
        self.labHistogram.setMinimumSize(QtCore.QSize(250, 100))
        self.labHistogram.setObjectName("labHistogram")
        self.verticalLayout.addWidget(self.labHistogram)
        self.labFinal = QtWidgets.QLabel(Form)
        self.labFinal.setMinimumSize(QtCore.QSize(250, 100))
        self.labFinal.setObjectName("labFinal")
        self.verticalLayout.addWidget(self.labFinal)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem6)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Process Kiln Images"))
        self.btnPrevious.setText(_translate("Form", "Previous"))
        self.btnNext.setText(_translate("Form", "Next"))
        self.btnGreyScale.setText(_translate("Form", "Grey Scale"))
        self.btnHistogram.setText(_translate("Form", "Histogram"))
        self.label_2.setText(_translate("Form", "Threshold: "))
        self.label_3.setText(_translate("Form", "Sigma:"))
        self.btnApplyMask.setText(_translate("Form", "Apply Mask"))
        self.btnFindRegions.setText(_translate("Form", "Find Regions"))
        self.label_5.setText(_translate("Form", "Digits:"))
        self.pushButton_5.setText(_translate("Form", "Split and Save"))
        self.labOriginal.setText(_translate("Form", "TextLabel"))
        self.labHistogram.setText(_translate("Form", "TextLabel"))
        self.labFinal.setText(_translate("Form", "TextLabel"))

